#!/bin/sh

temp="Temperature (Celcius Fahrenheit)"
conc="Concentration (mmol mg/dL)"
currency="Currency Money (Dollar SEK)"
distance="Distance (miles KM)"

menu="tofi -c $HOME/.config/tofi/configA"
scriptFolder="$HOME/.config/scripts"

choice=$(
  printf "%s\n" \
    "$temp" \
    "$conc" \
    "$currency" \
    "$distance" \
  | $menu --prompt "Choose converter: ")

#choice=$( "Temperature (Celcius Fahrenheit)" | $menu --prompt "Choose converter: " ' <<< ' 2>/dev/null)
case "$choice" in
    "$temp") 
        bash $HOME/$scriptFolder/convert_temperature.sh
	;;
    "$conc") 
        bash $HOME/$scriptFolder/convert_concentration.sh
	;;
    "$currency") 
        bash $HOME/$scriptFolder/convert_currency.sh
	;;
    "$distance") 
        bash $HOME/$scriptFolder/convert_distance.sh
	;;
esac

