windowrule {
    name = float
		match:class = qt5ct|qt6ct|kvantummanager|nwg-look|org\.kde\.ark|pavucontrol|blueman-manager|nm-(applet|connection-editor)|org\.kde\.polkit-kde-authentication-agent-1
    float = true
}

