# XWayland apps (often misbehave)
windowrule {
    name = xwayland
		match:class = xwayland:1
    no_blur = true
}

# Legacy Electron / Java apps
windowrule {
    name = legacy_electron_and_java
		#match = xwayland:1 class:^(Spotify|Arduino IDE)$
		match:class = xwayland:1 Spotify|Arduino IDE
    opacity = 0.75 0.75
}

