windowrule {
    name= core_apps
		match:class = Thorium-browser
    opacity = 0.90 0.90
}

windowrule {
    name = development_and_tools
		match:class = Code|Arduino IDE|dev\.warp\.Warp|obsidian|kitty|org\.gnome\.Nautilus|org\.kde\.ark
    opacity = 0.80 0.80
}

windowrule {
		name = theming_and_config
    match:class = qt5ct|qt6ct|kvantummanager|nwg-look
    opacity = 0.80 0.80
}

windowrule {
		name = system_utilities
    match:class = pavucontrol|blueman-manager|nm-(applet|connection-editor)|org\.kde\.polkit-kde-authentication-agent-1|polkit-gnome-authentication-agent-1|org\.freedesktop\.impl\.portal\.desktop\.(gtk|hyprland)
    opacity = 0.80 0.70
}

windowrule {
		name = spotify_edge_cases_A
    match:class = Spotify
    opacity = 0.70 0.70
}

windowrule {
		name = spotify_edge_cases_B
    match:class = initialTitle:^(Spotify Free)
    opacity = 0.70 0.70
}

windowrule {
		name = floating_rules
    match:class = !class:Floating
    opacity = 1.0
    #tint = 0x00000088
}




