# =========================
# Global metadata
# =========================
meta:
  name: desktop
  description: "Desktop workstation install"
  version: 1

# =========================
# Target system
# =========================
system:
  distro: cachyos          # arch | cachyos | debian | fedora
  arch: x86_64          # informational for now

# =========================
# Feature selections
# =========================
features:
  window_manager:
    enabled: true
    choice: hyprland
    #choice: hyprland     # hyprland | mangowc

  nvidia:
    enabled: true
    driver: 580xx        # 580xx | latest | none

  gaming:
    enabled: true

  bluetooth:
    enabled: true

  android:
    enabled: false

  kvm:
    enabled: true

# =========================
# Execution behavior
# =========================
execution:
  dry_run: false
  non_interactive: false
  confirm: true
