profiles:
  desktop:
    WM: Hyprland
    NVIDIA: 580xx
    GAMING: yes
    BLUETOOTH: yes
    ANDROID: yes
    KVM: yes

  laptop:
    WM: Hyprland
    NVIDIA: Latest release
    GAMING: no
    BLUETOOTH: yes
    ANDROID: yes
    KVM: no

always:
  - git
  - stow
  - yay
  - unzip
  - zen-browser

aur:
  - tofi
  - neovim-nightly-bin

fonts:
  - ~/dotfiles/Other/DejaVuSansMono.zip

dotfiles:
  - repo: git@github.com:chrisnordborg/dotfiles.git
    dest: ~/
  - repo: git@github.com:chrisnordborg/wallpapers.git
    dest: ~/
