windowrule {
   	name = terminal
		match:class = kitty
		workspace = 1
}

windowrule {
		name = browser
    match:title = Zen Browser
    workspace = 3
}

windowrule {
		name = notes
    match:class = obsidian
    workspace = 4
}

windowrule {
		name = music
    match:class = rhythmbox|spotify
    workspace = 5
}

windowrule {
		name = games
    match:class = steam
    workspace = 10
}

