always:
  - setup_git
  - setup_ssh
  - git_repos_set_remote_origin
  - remove_files_before_stow
  - stow_dotfiles

desktop:
  - move_fstab_desktop
  - move_keyd_config

unused:
  - ram_diagnostics_efi
  - dual_kernel_configurations
