profiles:
  desktop:
    OS: CachyOS
    WM:
      - Hyprland
    NVIDIA: 580xx
    GAMING: yes
    BLUETOOTH: yes
    ANDROID: yes
    KVM: yes
  laptop:
    OS: CachyOS
    WM:
      - Hyprland
      - MangoWC
    NVIDIA: LatestRelease
    GAMING: no
    BLUETOOTH: yes
    ANDROID: yes
    KVM: no
