# Optional: external references for dotfiles, font zips and others
dotfiles:
  - name: dotfiles
    repo: git@github.com:chrisnordborg/dotfiles.git
    dest: ~/
  - name: wallpapers
    repo: git@github.com:chrisnordborg/wallpapers.git
    dest: ~/

fonts:
  - name: DejaVuSansMono
    path: ~/dotfiles/Other/DejaVuSansMono.zip
    dest: /usr/share/fonts
