# GTK / Qt dialogs
windowrule {
    name = prompts
		match:title = Open|Save|Preferences|Settings|Authentication
    float = true
    center = true
}

# File pickers
windowrule {
    name = file_pickers
		match:class = org\.gnome\.GtkFileChooserDialog|xdg-desktop-portal
    float = true
    center = true
}

