# Music overlay
windowrule {
    name = music
		match:class = Spotify|rhythmbox
    workspace = special:music
}

# Quick scratch terminal
#windowrule {
#    name = scratch_terminal
#		match:class = kitty
#    #title = scratch$
#    workspace = special:scratch
#}

