[bar/mybar]
width = 100%
height = 30 
offset-y = 0
#background = #222222
#foreground = #ffffff
font-0 = "monospace:size=11"
#font-0 = "DejaVuSansM Nerd Font Mono:size=11;1"
#font-0 = "DejaVu Sans Mono:size=10;1"
font-1 = "Font Awesome 6 Free:style=Solid:size=10"
font-2 = "Font Awesome 6 Brands:style=Regular:size=10"
font-3 = "Nerd Font:style=Regular:size=10"
modules-left = i3
modules-center = date timer
;'battery' could also be added under modules-right on a laptop.
modules-right = cpu memory volume network battery

; Remove this line if you want i3's bar too
;override-redirect = true
wm-restack = i3


[module/i3]
type = internal/i3
format = <label-state>
index-sort = true
wrapping-scroll = false
pin-workspaces = true

##label-focused = %icon% %name%
##label-unfocused = %icon% %name%
##label-visible = %icon% %name%
##label-urgent = %icon% %name%
##label-focused-align = center
##label-unfocused-align = center

label-focused = %index%
label-unfocused = %index%
label-visible = %index%
label-urgent = %index%
label-focused-padding = 2
label-unfocused-padding = 2
label-visible-padding = 2
label-urgent-padding = 2
label-focused-foreground = #ffffff
label-focused-background = #b52020


[module/date]
;type = internal/date
type = custom/script
exec = ~/.config/polybar/scripts/date.sh
interval = 1
;format = "  %Y-%m-%d  %H:%M:%S"
format-underline = #5294e2

[module/timer]
type = custom/script
exec = cat /tmp/status_bar_timer.txt 2>/dev/null || echo "⏰"
tail = true
interval = 1
format = <label>
format-prefix = "⏰ "
format-underline = #a3be8c
label = %output%

[module/cpu]
;type = internal/cpu
type = custom/script
exec = ~/.config/polybar/scripts/cpu.sh
interval = 2
;format = "  %load%" 
format-underline = #b58900

[module/memory]
;type = internal/memory
type = custom/script
exec = ~/.config/polybar/scripts/memory.sh
interval = 2
;format = "  %used% / %total%" 
format-underline = #2aa198

[module/volume]
type = custom/script
exec = ~/.config/polybar/scripts/volume.sh
interval = 1
click-left = bash ~/.config/scripts/audio_output_switch.sh dmenu
click-right = pavucontrol
format-underline = #859900

[module/network]
;type = internal/network
type = custom/script
exec = ~/.config/polybar/scripts/network.sh
;for desktop pc with ethernet connection
;interface = eno1
;for laptop pc with wifi connection
;interface = wlp2s0
interval = 5
format-connected = "  %output%"
format-disconnected = Offline
format-underline = #6c71c4

[module/battery]
type = custom/script
exec = ~/.config/polybar/scripts/battery.sh
interval = 30
format-underline = #d33682

